"""empty message

Revision ID: 138ad6638c1e
Revises: 32ab43974f1a
Create Date: 2014-11-13 21:47:03.585013

"""

# revision identifiers, used by Alembic.
revision = '138ad6638c1e'
down_revision = '32ab43974f1a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('uuid', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'user', ['uuid'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user')
    op.drop_column('user', 'uuid')
    ### end Alembic commands ###
