"""empty message

Revision ID: 17ca3c32618a
Revises: 218cf8773bd4
Create Date: 2014-11-17 16:20:29.156133

"""

# revision identifiers, used by Alembic.
revision = '17ca3c32618a'
down_revision = '218cf8773bd4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('image_url_2', sa.String(length=2048), nullable=True))
    op.add_column('place', sa.Column('thumbnail_url_2', sa.String(length=2048), nullable=True))
    op.drop_column('place_image', 'thumbnail_url')
    op.drop_column('place_image', 'image_url')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place_image', sa.Column('image_url', mysql.TEXT(), nullable=True))
    op.add_column('place_image', sa.Column('thumbnail_url', mysql.TEXT(), nullable=True))
    op.drop_column('place', 'thumbnail_url_2')
    op.drop_column('place', 'image_url_2')
    ### end Alembic commands ###
