"""empty message

Revision ID: 185720bd944
Revises: 58d8363c47e8
Create Date: 2014-11-10 19:26:02.813963

"""

# revision identifiers, used by Alembic.
revision = '185720bd944'
down_revision = '58d8363c47e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
