"""empty message

Revision ID: 1a7dce8b5185
Revises: 4262a54d7278
Create Date: 2014-11-12 16:40:07.897633

"""

# revision identifiers, used by Alembic.
revision = '1a7dce8b5185'
down_revision = '4262a54d7278'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
