"""empty message

Revision ID: 218cf8773bd4
Revises: 189e7267d74d
Create Date: 2014-11-17 14:47:15.185861

"""

# revision identifiers, used by Alembic.
revision = '218cf8773bd4'
down_revision = '189e7267d74d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place_image', sa.Column('user_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place_image', 'user_id')
    ### end Alembic commands ###
