"""empty message

Revision ID: 2691561059ac
Revises: 4371ecd5709e
Create Date: 2014-11-14 00:28:11.636047

"""

# revision identifiers, used by Alembic.
revision = '2691561059ac'
down_revision = '4371ecd5709e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    ### end Alembic commands ###
