"""empty message

Revision ID: 2ad959b03fa0
Revises: 2f011879173d
Create Date: 2014-11-17 17:16:00.892255

"""

# revision identifiers, used by Alembic.
revision = '2ad959b03fa0'
down_revision = '2f011879173d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('best_place_image_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'best_place_image_id')
    ### end Alembic commands ###
