"""empty message

Revision ID: 2d4e0fe74122
Revises: 1a7dce8b5185
Create Date: 2014-11-12 16:41:06.252283

"""

# revision identifiers, used by Alembic.
revision = '2d4e0fe74122'
down_revision = '1a7dce8b5185'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
