"""empty message

Revision ID: 2f011879173d
Revises: 512cd571e7c3
Create Date: 2014-11-17 17:15:16.996086

"""

# revision identifiers, used by Alembic.
revision = '2f011879173d'
down_revision = '512cd571e7c3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'best_image_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('best_image_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
