"""empty message

Revision ID: 30f3e87d189a
Revises: 2d4e0fe74122
Create Date: 2014-11-12 16:44:41.301356

"""

# revision identifiers, used by Alembic.
revision = '30f3e87d189a'
down_revision = '2d4e0fe74122'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('best_comment_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'best_comment_id')
    ### end Alembic commands ###
