"""empty message

Revision ID: 32ab43974f1a
Revises: 38a94f4e385d
Create Date: 2014-11-13 17:01:57.622398

"""

# revision identifiers, used by Alembic.
revision = '32ab43974f1a'
down_revision = '38a94f4e385d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user')
    ### end Alembic commands ###
