"""empty message

Revision ID: 351e4ba8beee
Revises: 5a70ab66ee8e
Create Date: 2014-11-17 17:04:23.217792

"""

# revision identifiers, used by Alembic.
revision = '351e4ba8beee'
down_revision = '5a70ab66ee8e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('best_image_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'best_image_id')
    ### end Alembic commands ###
