"""empty message

Revision ID: 38a94f4e385d
Revises: 392f81fd5ffe
Create Date: 2014-11-13 16:44:22.472908

"""

# revision identifiers, used by Alembic.
revision = '38a94f4e385d'
down_revision = '392f81fd5ffe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
