"""empty message

Revision ID: 392f81fd5ffe
Revises: c71016735cd
Create Date: 2014-11-13 16:31:23.151334

"""

# revision identifiers, used by Alembic.
revision = '392f81fd5ffe'
down_revision = 'c71016735cd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place_picture', sa.Column('place_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place_picture', 'place_id')
    ### end Alembic commands ###
