"""empty message

Revision ID: 40592a4745ee
Revises: 1144f1bcec08
Create Date: 2014-11-13 16:29:00.271659

"""

# revision identifiers, used by Alembic.
revision = '40592a4745ee'
down_revision = '1144f1bcec08'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
