"""empty message

Revision ID: 4262a54d7278
Revises: 5731ea92f6f3
Create Date: 2014-11-12 16:37:08.898361

"""

# revision identifiers, used by Alembic.
revision = '4262a54d7278'
down_revision = '5731ea92f6f3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
