"""empty message

Revision ID: 4371ecd5709e
Revises: 5651c8539e9f
Create Date: 2014-11-14 00:19:00.815391

"""

# revision identifiers, used by Alembic.
revision = '4371ecd5709e'
down_revision = '5651c8539e9f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.drop_column('user', 'email_authorized')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_authorized', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('user', 'email_verified')
    ### end Alembic commands ###
