"""empty message

Revision ID: 479beb9cc90d
Revises: 5197f406b649
Create Date: 2014-11-12 17:02:32.480219

"""

# revision identifiers, used by Alembic.
revision = '479beb9cc90d'
down_revision = '5197f406b649'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
