"""empty message

Revision ID: 512cd571e7c3
Revises: 351e4ba8beee
Create Date: 2014-11-17 17:11:45.544348

"""

# revision identifiers, used by Alembic.
revision = '512cd571e7c3'
down_revision = '351e4ba8beee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
