"""empty message

Revision ID: 5197f406b649
Revises: 30f3e87d189a
Create Date: 2014-11-12 16:59:37.261305

"""

# revision identifiers, used by Alembic.
revision = '5197f406b649'
down_revision = '30f3e87d189a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
