"""empty message

Revision ID: 51cce1f22d4
Revises: 58399b198aa1
Create Date: 2014-11-17 16:22:41.801598

"""

# revision identifiers, used by Alembic.
revision = '51cce1f22d4'
down_revision = '58399b198aa1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('image_url', sa.String(length=2048), nullable=True))
    op.add_column('place', sa.Column('thumbnail_url', sa.String(length=2048), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'thumbnail_url')
    op.drop_column('place', 'image_url')
    ### end Alembic commands ###
