"""empty message

Revision ID: 5731ea92f6f3
Revises: 185720bd944
Create Date: 2014-11-12 16:34:35.301645

"""

# revision identifiers, used by Alembic.
revision = '5731ea92f6f3'
down_revision = '185720bd944'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
