"""empty message

Revision ID: 58399b198aa1
Revises: 17ca3c32618a
Create Date: 2014-11-17 16:21:43.585648

"""

# revision identifiers, used by Alembic.
revision = '58399b198aa1'
down_revision = '17ca3c32618a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'thumbnail_url')
    op.drop_column('place', 'image_url')
    op.add_column('place_image', sa.Column('image_url', sa.String(length=2048), nullable=True))
    op.add_column('place_image', sa.Column('thumbnail_url', sa.String(length=2048), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place_image', 'thumbnail_url')
    op.drop_column('place_image', 'image_url')
    op.add_column('place', sa.Column('image_url', mysql.TEXT(), nullable=True))
    op.add_column('place', sa.Column('thumbnail_url', mysql.TEXT(), nullable=True))
    ### end Alembic commands ###
