"""empty message

Revision ID: 58d8363c47e8
Revises: 3c5922646f23
Create Date: 2014-11-06 20:21:12.102829

"""

# revision identifiers, used by Alembic.
revision = '58d8363c47e8'
down_revision = '3c5922646f23'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('rate_count', sa.Integer(), nullable=True))
    op.add_column('place', sa.Column('rate_sum', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'rate_sum')
    op.drop_column('place', 'rate_count')
    ### end Alembic commands ###
