"""empty message

Revision ID: 5a70ab66ee8e
Revises: 51cce1f22d4
Create Date: 2014-11-17 16:23:16.185254

"""

# revision identifiers, used by Alembic.
revision = '5a70ab66ee8e'
down_revision = '51cce1f22d4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'image_url_2')
    op.drop_column('place', 'thumbnail_url_2')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('thumbnail_url_2', mysql.VARCHAR(length=2048), nullable=True))
    op.add_column('place', sa.Column('image_url_2', mysql.VARCHAR(length=2048), nullable=True))
    ### end Alembic commands ###
