"""empty message

Revision ID: c71016735cd
Revises: 40592a4745ee
Create Date: 2014-11-13 16:29:23.908055

"""

# revision identifiers, used by Alembic.
revision = 'c71016735cd'
down_revision = '40592a4745ee'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('place_picture', 'place_id')
    ### end Alembic commands ###
    pass


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place_picture', sa.Column('place_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
